[package]
name = "fent_ecs"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Revilo126"]
description = "Simple ECS library"
repository = "https://github.com/Revilo126/fent_ecs"
readme = "README.md"
keywords = ["ecs"]
categories = ["data-structures"]

[workspace]
members = ["fent_derive"]

[dependencies]
# Internal
fent_derive = { path = "fent_derive", version = "0.1.0" }

# External
log = "0.4.34"

[dev-dependencies]
criterion = "0.8.2"


[[test]]
name = "integration"
path = "tests/lib.rs"

[[bench]]
name = "storage"
harness = false
