[package]
name = "fent_derive"
version = "0.1.1"
edition = "2024"
description = "Provides macros for fent_ecs"
license = "MIT"
repository = "https://github.com/Revilo126/fent_ecs"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.3", features = ["full", "extra-traits"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"
